### ISSUE TITLE
UEFI boot test fails on s390x

### ISSUE THREAD

**Issue by bdrung** [dracut-ng/dracut-ng#976]
**Describe the bug**

The UEFI boot test fails on s390x with:

```
Traceback (most recent call last):
  File "/usr/bin/ukify", line 1746, in <module>
    main()
  File "/usr/bin/ukify", line 1732, in main
    opts = parse_args()
           ^^^^^^^^^^^^
  File "/usr/bin/ukify", line 1727, in parse_args
    finalize_options(opts)
  File "/usr/bin/ukify", line 1675, in finalize_options
    opts.efi_arch = guess_efi_arch()
                    ^^^^^^^^^^^^^^^^
  File "/usr/bin/ukify", line 90, in guess_efi_arch
    raise ValueError(f'Unsupported architecture {arch}')
ValueError: Unsupported architecture s390x
```

ukify should not fail that way, but we should skip the UEFI boot test on s390x.

**Distribution used**
Ubuntu

**Dracut version**
Commit f4aaee95a5195a6a80ca08a4e0dfd989237be756

**Comment by bdrung** [comment]
I also created https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2088336
